//@ts-ignore
import {initializeMIPS as _initializeMIPS, getInstructionSet as _getInstructionSet} from './generated/mars'
//@ts-ignore Generated by the Java build.
import {makeMipsFromFilesWithOptions as _makeMipsFromFilesWithOptions, analyzeGnuUnit as _analyzeGnuUnit} from './generated/mars'

/**
 * The assembly dialect of a program. `mars` is the educational MARS dialect with its macros and
 * pseudo instructions; `gnu-compiler-v1` is the bounded GNU assembler subset GCC writes for MIPS32.
 */
export type AssemblerProfile = 'mars' | 'gnu-compiler-v1'

/**
 * GNU compiler assembly members and the index naming the member that defines each global. A Build
 * pulls a member only to resolve a global the program uses and does not define, as ld pulls members
 * out of an archive, and keeps pulling for the globals those members use in turn. Members are always
 * assembled with the `gnu-compiler-v1` profile, whatever profile the program uses, and their paths
 * never meet the program's Files.
 */
export type RuntimeLibrary = {
    /** Canonical member path to its source. */
    members: Record<string, string>
    /** Global symbol to the path of the member defining it. */
    index: Record<string, string>
    /**
     * Globals the library supplies even to a weak reference, which otherwise pulls no member: GCC
     * refers to `__cxa_pure_virtual` weakly from every abstract class's vtable.
     */
    resolveWeak?: string[]
}

export type AssemblyOptions = {
    assemblerProfile?: AssemblerProfile
    /**
     * The global execution starts at instead of `main`. The link must define it, and with a library
     * it pulls its own member, as ld's entry symbol does: `_start` brings in a library's startup code.
     */
    entrySymbol?: string
    /** Libraries searched in order: the first one whose index names a symbol supplies it. */
    libraries?: RuntimeLibrary[]
}

/** The globals one GNU compiler unit defines and the ones it uses without defining. */
export type GnuUnitSymbols = {
    /** Globals the unit defines, strong or weak. */
    defined: string[]
    /** The defined globals that are weak. */
    weak: string[]
    /** Globals the unit uses without defining, other than weak references, which pull nothing. */
    references: string[]
    /** Why the unit could not be parsed, as `path:line: message`; empty when it parsed. */
    errors: string[]
}


export type JsInstructionToken = {
    /** One-based column in the processed source line. */
    sourceColumn: number;
    value: string;
    type: string
}



/**
 * Why a run call (`step`, `simulate`, `simulateWithLimit`, `simulateWithBreakpoints`,
 * `simulateWithBreakpointsAndLimit`) stopped. The same enum, with the same values, as
 * `@specy/risc-v`'s: MARS numbered its reasons from 1 and had one for both pause and stop.
 */
export enum StopReason {
    /** No run call has stopped since the program was initialized; only `getStopReason` reports it. */
    NONE = -1,
    /** A breakpoint address was reached; the instruction there has not run. */
    BREAKPOINT,
    /** Never returned: a runtime failure rejects the run call with a `RuntimeError` instead. */
    EXCEPTION,
    /** The instruction limit was reached, which is what a single `step()` ends on. */
    MAX_STEPS,
    /** An exit service (10 or 17) ran, or the program had already exited and nothing ran. */
    NORMAL_TERMINATION,
    /** The program ran off the end of its code: there is no statement at the program counter. */
    CLIFF_TERMINATION,
    /** Not reachable through this package. */
    PAUSE,
    /** Not reachable through this package. */
    STOP
}

/**
 * What a `RuntimeError` was:
 * - `exception`: a MIPS exception the program had no handler for: an address error, an arithmetic
 *   overflow, a trap, `break`, an instruction fetch outside the program.
 * - `syscall`: a syscall refused its service number, arguments or input, such as "invalid integer
 *   input (syscall 5)" or "invalid or unimplemented syscall service: 99".
 * - `handler`: a host handler or memory observer threw, rejected or broke its contract; its `cause`
 *   is what it threw or rejected with.
 * - `internal`: the simulator itself failed.
 */
export type RuntimeErrorKind = 'exception' | 'syscall' | 'handler' | 'internal'

/**
 * The error a run call rejects with when the program fails at runtime: an `Error` named
 * `RuntimeError` with typed fields, so that a host never parses its text. Any other rejection,
 * such as a run call on a program that did not assemble, is the plain error it is.
 */
export interface RuntimeError extends Error {
    readonly name: 'RuntimeError'
    readonly kind: RuntimeErrorKind
    /**
     * The address of the instruction that failed, or of the program counter that could not be
     * fetched, as a signed 32 bit int like `JsProgramStatement.address`.
     */
    readonly address: number
    /** The failing statement's source file, or null when there is no statement. */
    readonly sourcePath: string | null
    /** The failing statement's one-based line in `sourcePath`, or null. */
    readonly line: number | null
    /**
     * MARS's own words, without the location: "Runtime exception at 0x00400004: invalid or
     * unimplemented syscall service: 40", "Handler readInt did not return a string".
     */
    readonly message: string
    /** For a `handler` failure, what the handler threw or rejected with. */
    readonly cause?: unknown
}

/** Whether a run call's rejection is a typed `RuntimeError`. */
export function isRuntimeError(error: unknown): error is RuntimeError {
    return error instanceof Error && error.name === 'RuntimeError' && typeof (error as RuntimeError).kind === 'string'
}

/** The kind of message dialog syscall 55 asks for; any other value of $a1 asks for a plain message. */
export enum DialogType {
    PLAIN_MESSAGE = -1,
    ERROR_MESSAGE = 0,
    INFORMATION_MESSAGE = 1,
    WARNING_MESSAGE = 2,
    QUESTION_MESSAGE = 3
}

export enum ConfirmResult {
    YES = 0,
    NO = 1,
    CANCEL = 2
}

/**
 * The handlers a program's syscalls reach the outside world through, each as its arguments and its
 * answer. The syscalls own each service's semantics, as MARS defines them: they format what they
 * print and parse what they read, so a handler only moves text and bytes. Bytes cross as plain
 * arrays of numbers from 0 to 255.
 */
export type HandlerMap = {
    /**
     * Syscall 13: open a file, with `flags` 0 to read and 1 to write, `append` set for flags 9. The
     * path is the program's string decoded from UTF-8. Answer with the new file descriptor, or -1
     * when the file cannot be opened.
     */
    openFile: {in: [filename: string, flags: number, append: boolean], out: number}
    /** Syscall 16: close a file descriptor that `openFile` returned. */
    closeFile: {in: [fileDescriptor: number], out: void}
    /**
     * Syscall 15 on a file descriptor that `openFile` returned: write the bytes. Answer with the
     * number of bytes written, or -1 when the write failed; the program receives it in $v0.
     */
    writeFile: {in: [fileDescriptor: number, buffer: number[]], out: number}
    /**
     * Syscall 14 on a file descriptor that `openFile` returned: read at most `length` bytes. Answer
     * with `[count, bytes]`, where a count of 0 is the end of the file and -1 a failed read.
     */
    readFile: {in: [fileDescriptor: number, length: number], out: [count: number, buffer: number[]]}
    /**
     * Syscall 50: a Yes, No and Cancel question. Cancel reaches the program as 2. Every dialog's
     * message is the program's string decoded from UTF-8.
     */
    confirm: {in: [message: string], out: ConfirmResult}
    /**
     * Syscalls 51 to 54: ask for a line of text. Answer with the text, or null when the user cancels,
     * which the program receives as status -2. The syscall parses the text itself, as MARS does;
     * 54 stores it as UTF-8, measuring the buffer in bytes.
     */
    inputDialog: {in: [message: string], out: string | null}
    /** Syscalls 55 to 59: show a message. The program waits until the handler settles. */
    outputDialog: {in: [message: string, type: DialogType], out: void}
    /**
     * Syscall 5: the line typed. The syscall trims it and parses it as Java's `Integer.parseInt`
     * does; anything else stops the program with "invalid integer input (syscall 5)".
     */
    readInt: {in: [], out: string}
    /**
     * Syscall 6: the line typed. The syscall trims it and parses it as Java's `Float.parseFloat`
     * does; anything else stops the program with "invalid float input (syscall 6)".
     */
    readFloat: {in: [], out: string}
    /**
     * Syscall 7: the line typed. The syscall trims it and parses it as Java's `Double.parseDouble`
     * does; anything else stops the program with "invalid double input (syscall 7)".
     */
    readDouble: {in: [], out: string}
    /**
     * Syscall 8: the line typed. The syscall stores it as UTF-8, as RARS does: at most the buffer's
     * length less one characters, then at most that many bytes of them, so a character can be cut
     * where the buffer ends.
     */
    readString: {in: [], out: string}
    /**
     * Syscall 12: the character typed, Enter as `"\n"`. The syscall takes the first UTF-16 unit of the
     * answer, as MARS and RARS do (`é` reads as 233, an emoji as its high surrogate); an empty answer
     * stops the program with "invalid char input (syscall 12)".
     */
    readChar: {in: [], out: string}
    /**
     * Program output: the text every print syscall (1 to 4, 11 and 34 to 36) formats, exactly as
     * MARS prints it on Java 21, so a float prints `1.0` and `1.0E-5`. Print string (4) decodes the
     * string from UTF-8, where MARS reads one byte per character; print char (11) prints the
     * character numbered by the low byte of $a0, as MARS and RARS do.
     */
    printString: {in: [text: string], out: void}
    /**
     * Syscall 32: the program asks to be suspended for this many milliseconds. Return a promise
     * that settles when the wait is over to suspend the simulation without blocking the host.
     */
    sleep: {in: [milliseconds: number], out: void}
    /**
     * Syscall 30: the program time in milliseconds, split by the syscall into $a0 (low word) and
     * $a1 (high word). Answer with `Date.now()` for a live run, or with a virtual clock for a
     * scripted one, so that elapsed-time output stays reproducible.
     */
    time: {in: [], out: number}
    /**
     * A read of standard input (descriptor 0): answer with the bytes left over from the current
     * line or else one new line, at most `length` of them, as `[count, bytes]`. A count of 0 is end
     * of input and -1 a failed read. Return a promise to wait for the user.
     */
    stdIn: {in: [length: number], out: [count: number, buffer: number[]]}
    /**
     * Syscall 62 (lseek, an extension numbered as RARS numbers it): move an open file's position.
     * `whence` is 0 from the start, 1 from the current position, 2 from the end. Answer with the new
     * position, or -1 when the seek fails.
     */
    seekFile: {in: [fileDescriptor: number, offset: number, whence: number], out: number}
    /** Syscall 15 on descriptor 1: the bytes written to standard output. */
    stdOut: {in: [buffer: number[]], out: void}
    /** Syscall 15 on descriptor 2: the bytes written to standard error. */
    stdErr: {in: [buffer: number[]], out: void}
    /**
     * Syscalls 41 to 44, on the first use of a generator the program has not seeded with service
     * 40: the seed it starts from, as `new java.util.Random(seed)` takes it, a whole number from 0
     * to 2^48 - 1 (every seed a Java long can hold scrambles to the state one of these does).
     * `index` is the generator's number from $a0. Answer with host randomness for a live run, or
     * with a fixed seed for a scripted one, so that a Testcase gets the same numbers every time.
     *
     * Optional: without it a generator starts from host randomness, as in MARS. The generators
     * implement `java.util.Random` exactly, so a seeded program prints the numbers MARS prints.
     */
    randomSeed: {in: [index: number], out: number}
}

/**
 * Notified after a write anywhere in an observed address range.
 *
 * `length` is the width of the access in bytes (4, 2 or 1) and `value` is what the program stored,
 * so a byte or halfword store reports only the bytes it touched; a peripheral that mirrors whole
 * words should re-read the containing word with `readMemoryBytes` rather than trust `value`.
 *
 * Both `address` and `value` are signed 32 bit integers, as the guest holds them: the register at
 * `0xffff000c` arrives as `-65524`, and a pixel word with its high bit set arrives negative too.
 * Apply `>>> 0` wherever the unsigned form is wanted.
 */
export type MemoryWriteObserver = (address: number, length: number, value: number) => void

/**
 * Notified after a read or a write of one observed word, with the same signed 32 bit numbers as
 * `MemoryWriteObserver`. `value` is the value the program read or stored; on a read it is what
 * memory held *before* the observer ran, so a register whose value is consumed by reading it must
 * be reloaded from the handler for the next read.
 */
export type MemoryAccessObserver = (address: number, value: number) => void

/** Identifies one registration, for `removeMemoryObserver`. */
export type MemoryObserverHandle = number


export type JsInstruction = {
    name: string;
    example: string;
    description: string;
    tokens: JsInstructionToken[];
}

export type MipsTokenizedLine = {
    sourcePath: string;
    /** One-based line in `sourcePath`. */
    sourceLine: number;
    /** Exact line supplied in the source set. */
    source: string;
    /** Line after assembler substitutions such as `.eqv`. */
    processedSource: string;
    tokens: JsInstructionToken[]
}

export type MIPSSourceLocation = {
    sourcePath: string
    /** One-based line in `sourcePath`. */
    sourceLine: number
}

export type MIPSSourceSet = Readonly<Record<string, string>>

export type MIPSAssembleError = {
    isWarning: boolean
    message: string
    macroExpansionTrace: MIPSSourceLocation[]
    sourcePath: string
    /** One-based line in `sourcePath`. */
    sourceLine: number
    /** One-based column in `sourcePath`. Zero only for diagnostics without a source location. */
    sourceColumn: number
}

export type MIPSAssembleResult = {
    report: string
    errors: MIPSAssembleError[]
    /** True only when at least one diagnostic is a real error; warnings alone leave the assembled program runnable. */
    hasErrors: boolean
    /** True when at least one diagnostic is a warning. */
    hasWarnings: boolean
}


/**
 * The coprocessor 0 register numbers, in the order `getCoprocessor0Values` returns their values
 * and `setCoprocessor0Value` names them: `$8 (vaddr)`, `$12 (status)`, `$13 (cause)`,
 * `$14 (epc)`. Coprocessor 0 implements only these four, so a register's number is not its
 * position in the array.
 */
export const MIPS_COPROCESSOR0_REGISTER_NUMBERS = [8, 12, 13, 14] as const

export class MIPS {
    public static readonly assemblerProfiles: readonly AssemblerProfile[] = Object.freeze(['mars', 'gnu-compiler-v1'])
    public static makeMipsFromFiles = makeMipsFromFiles
    public static initializeMIPS = initializeMIPS
    /**
     * The globals one `gnu-compiler-v1` unit defines and uses, without laying it out or touching
     * memory, for building a library index.
     */
    public static analyzeGnuUnit(path: string, source: string): GnuUnitSymbols {
        MIPS.initializeMIPS()
        const result = _analyzeGnuUnit(path, source)
        return {
            defined: Array.from(result.defined as string[]),
            weak: Array.from(result.weak as string[]),
            references: Array.from(result.references as string[]),
            errors: Array.from(result.errors as string[]),
        }
    }
    public static getInstructionSet(){
        return _getInstructionSet() as JsInstruction[]
    }
}

export type JsMipsStackFrame = {
    /**
     * The program counter value at the moment the stack frame was created.
     */
    pc: number;
    /**
     * The address of the target instruction.
     */
    toAddress: number;
    /**
     * The stack pointer value at the moment the stack frame was created.
     */
    sp: number;
    /**
     * The frame pointer value at the moment the stack frame was created.
     */
    fp: number;
    /**
     * The values of all registers at the moment the stack frame was created.
     */
    registers: number[];
}

/**
 * Represents a statement in the assembled program.
 */
export interface JsProgramStatement {
    /** Canonical path of the original source file. */
    readonly sourcePath: string;
    /**
     * The one-based line number in the original source file.
     */
    readonly sourceLine: number;
    /**
     * The memory address of the instruction.
     */
    readonly address: number;
    /**
     * The binary representation of the instruction.
     */
    readonly binaryStatement: number;
    /**
     * The original source code line.
     */
    readonly source: string;
    /**
     * The machine code representation of the instruction.
     */
    readonly machineStatement: string;


    /**
     * The assembly representation of the instruction.
     */
    readonly assemblyStatement: string;
}

/**
 * Enum representing the types of "undo" actions.
 */
export enum BackStepAction {
    MEMORY_RESTORE_RAW_WORD,
    MEMORY_RESTORE_WORD,
    MEMORY_RESTORE_HALF,
    MEMORY_RESTORE_BYTE,
    REGISTER_RESTORE,
    PC_RESTORE,
    COPROC0_REGISTER_RESTORE,
    COPROC1_REGISTER_RESTORE,
    COPROC1_CONDITION_CLEAR,
    COPROC1_CONDITION_SET,
    DO_NOTHING, // instruction does not write anything.
    /**
     * A whole Poke: every value one `beginPoke`/`endPoke` transaction wrote, restored together.
     * A Poke is a single back step, so it takes one slot of the undo size whatever it wrote.
     */
    POKE,
    /**
     * An exit service (10 or 17): undoing it leaves the program running on the syscall again.
     * `param1` is 1 if the program had already exited (never, as nothing runs after an exit),
     * `param2` the exit code it replaced and `newValue` the code the exit set.
     */
    EXIT_RESTORE,
    /**
     * A random service (40 to 44) advanced or reseeded generator `param1`: undoing it puts the
     * generator back, so that stepping the service again draws the same number. The generator's
     * state is the simulator's own, so `param2` and `newValue` are 0.
     */
    RANDOM_STREAM_RESTORE,
}

/**
 * Represents a back step in the simulation undo stack.
 */
export interface JsBackStep {
    /** Opaque decimal identity, unique across Undo, initialize and reassembly in this module. */
    readonly serial: string;
    /**
     * The action performed (e.g., register write, memory write).
     */
    readonly action: BackStepAction;

    /**
     * Information about the action
     */
    readonly param1: number;

    /**
     * Information about the action
     */
    readonly param2: number;

    /**
     * The other half of what this step restores: the value the write left, as the simulator saw it
     * at the moment of the write, beside the `param2` it replaced.
     *
     * - `REGISTER_RESTORE`, `COPROC0_REGISTER_RESTORE` and `COPROC1_REGISTER_RESTORE`: the whole
     *   value the write put in the register.
     * - `MEMORY_RESTORE_RAW_WORD` and `MEMORY_RESTORE_WORD`: the word left at the address.
     *   `MEMORY_RESTORE_HALF` and `MEMORY_RESTORE_BYTE`: the half or byte left there, in the low
     *   order bits, so that both values are read at the width the write was made.
     * - `PC_RESTORE`: the address the instruction set the program counter to, while `param1` is
     *   the address the restore puts back (`param2` is unused there, as it has always been).
     * - `EXIT_RESTORE`: the exit code the exit set.
     * - 0 for the actions that restore no value: `COPROC1_CONDITION_SET`, `COPROC1_CONDITION_CLEAR`,
     *   `DO_NOTHING` and `POKE`, whose own `writes` already carry both sides of every value, and
     *   `RANDOM_STREAM_RESTORE`, whose generator state is the simulator's own.
     *
     * A signed 32 bit int like `param2`, the way every register getter of this package reports a
     * value; read it unsigned with `newValue >>> 0`.
     */
    readonly newValue: number;
    /**
     * The program counter value before the action, or -1 for an action that belongs to no
     * instruction: a Poke, or a host write made before anything ran.
     */
    readonly pc: number;

    /**
     * Whether this step is a whole Poke rather than one effect of an instruction. It is the
     * discriminator this list needs, since a Poke and a pre-run host write both carry `pc` -1.
     */
    readonly isPoke: boolean;
}

/**
 * One value a Poke changed: a register, named the way this package's getters spell it, or a run of
 * consecutive memory bytes. `old` is what the simulator held when the write happened and `new` what
 * it held when the Poke was closed, so a value written twice inside one Poke reports its final
 * state.
 */
export type JsPokeWrite = JsPokeRegisterWrite | JsPokeMemoryWrite

/**
 * A register a Poke wrote. `name` is the register's own name: `$t0` for a general register, `$f2`
 * for an FPU register, `$13 (cause)` for a coprocessor 0 register - the spellings
 * `getRegistersValues`, `getCoprocessor1Values` and `getCoprocessor0Values` document - and
 * `flag 3` for one of the FPU condition flags. Both values are signed 32 bit ints, as every
 * register getter reports them; a condition flag is 0 or 1.
 */
export type JsPokeRegisterWrite = {
    readonly type: 'register'
    readonly name: string
    readonly old: number
    readonly new: number
}

/**
 * A run of consecutive memory bytes a Poke wrote, `address` being the first one, unsigned, and the
 * two arrays holding one byte (0 to 255) per address. A Poke that writes addresses that are not
 * adjacent reports one of these per run, by ascending address. Unlike `readMemoryBytes`, these are
 * ordinary JS arrays.
 */
export type JsPokeMemoryWrite = {
    readonly type: 'memory'
    readonly address: number
    readonly old: number[]
    readonly new: number[]
}

/**
 * One entry of the undo history: everything a single `undo()` reverts, which is either one executed
 * instruction or one Poke. Entries, their back steps and their writes are ordinary objects with own
 * properties, so a whole history can be cloned, serialized or deep-compared as it comes. An instruction that recorded several back steps - a `jal` restoring both
 * `$ra` and the program counter, a multiply writing `hi` and `lo` - is one entry with several
 * `steps`.
 */
export type JsUndoGroup = JsInstructionUndoGroup | JsPokeUndoGroup

/** One executed instruction, at the address `pc`. */
export type JsInstructionUndoGroup = {
    /** Opaque decimal identity, unique across Undo, initialize and reassembly in this module. */
    readonly serial: string;
    readonly kind: 'instruction'
    readonly pc: number
    /** The instruction's back steps, newest first. */
    readonly steps: JsBackStep[]
    /** Always empty: only a Poke reports writes. */
    readonly writes: readonly []
}

/**
 * One Poke: register or memory values written by the host between two instructions, recorded as a
 * step of its own. It belongs to no instruction, so `pc` is -1 and undoing it restores exactly what
 * `writes` lists, leaving the program counter, the call stack and everything else alone.
 */
export type JsPokeUndoGroup = {
    /** Opaque decimal identity, unique across Undo, initialize and reassembly in this module. */
    readonly serial: string;
    readonly kind: 'poke'
    readonly pc: -1
    /** The single back step the Poke is: one slot of the history, whatever the Poke wrote. */
    readonly steps: [JsBackStep]
    readonly writes: JsPokeWrite[]
}

/**
 * All MIPS register names.
 */
export type RegisterName =
    '$zero'
    | '$at'
    | '$v0'
    | '$v1'
    | '$a0'
    | '$a1'
    | '$a2'
    | '$a3'
    | '$t0'
    | '$t1'
    | '$t2'
    | '$t3'
    | '$t4'
    | '$t5'
    | '$t6'
    | '$t7'
    | '$s0'
    | '$s1'
    | '$s2'
    | '$s3'
    | '$s4'
    | '$s5'
    | '$s6'
    | '$s7'
    | '$t8'
    | '$t9'
    | '$k0'
    | '$k1'
    | '$gp'
    | '$sp'
    | '$fp'
    | '$ra';

type HandlerName = keyof HandlerMap


/**
 * A handler may return its result directly, or a promise of it. When a handler returns a promise
 * the simulation suspends until it settles, so IO can be backed by an async API (prompting the
 * user, reading a file, awaiting a worker) without blocking the event loop. If the promise
 * rejects, the pending `step`/`simulate*` call rejects too.
 */
type HandlerFn<K extends HandlerName> = (...args: HandlerMap[K]['in']) => HandlerMap[K]['out'] | Promise<HandlerMap[K]['out']>

/** The handlers a host may leave out: the simulator then does what MARS does on its own. */
export type OptionalHandlerName = 'randomSeed'

export type HandlerMapFns = {
    [K in Exclude<HandlerName, OptionalHandlerName>]: HandlerFn<K>
} & {
    [K in OptionalHandlerName]?: HandlerFn<K>
}

export function registerHandlers(mips: JsMips, handlers: HandlerMapFns) {
    for (const [name, handler] of Object.entries(handlers)) {
        mips.registerHandler(name as HandlerName, handler as HandlerFn<HandlerName>)
    }
}

export function unimplementedHandler(name: HandlerName) {
    return function () {
        throw new Error(`Handler ${name} is not implemented`)
    }
}

/**
 * Interface for interacting with a MIPS simulator.
 */
export interface JsMips {
    /**
     * Assembles the program.
     */
    assemble(): MIPSAssembleResult;

    /**
     * Initializes the simulator for a new run: the registers, the program counter, and the state
     * of the run - not exited, exit code 0, no stop reason, and the random generators forgotten, so
     * that each starts from a new seed on its first use. Assembling leaves the run state alone.
     * @param startAtMain If true, starts execution at the 'main' label. Otherwise, starts at the first instruction.
     */
    initialize(startAtMain: boolean): void;

    /**
     * Executes a single instruction.
     *
     * Resolves to why it stopped: `MAX_STEPS` normally, `NORMAL_TERMINATION` for an exit,
     * `CLIFF_TERMINATION` when the instruction was the program's last (or there was none to run).
     * A program that has exited runs nothing more and resolves to `NORMAL_TERMINATION` again.
     * Rejects with a `RuntimeError` when the program fails. The promise settles on a microtask
     * unless an IO handler returned a promise, in which case it settles once that handler and the
     * rest of the instruction have finished.
     */
    step(): Promise<StopReason>;

    /**
     * Why the last run call stopped: `NONE` when none has since the program was initialized, and
     * `EXCEPTION` after one rejected with a `RuntimeError`. Undo does not change it; read
     * `terminated` for whether the program can run.
     */
    getStopReason(): StopReason;

    /**
     * The program's exit code: exit2's (17) operand once it has run, 0 otherwise - after exit (10),
     * after running off the end, while the program runs. `initialize` resets it to 0, and undoing
     * the exit puts back the code before it.
     */
    readonly exitCode: number;


    /**
     * Gets the 8 FPU condition flags, element i being flag i, each 0 or 1. They are the FPU
     * register file's status flags: a compare instruction such as `c.lt.s` writes one.
     */
    getConditionFlags(): number[];

    /**
     * Sets one FPU condition flag. Outside a Poke the write is direct: it records no undo step, so
     * a preset value never becomes an entry the simulation can step back over. Inside a Poke it
     * joins the open transaction, as `flag N`.
     * @param flag The flag number, 0 to 7. Any other number throws.
     * @param value True to set the flag to 1, false to clear it to 0.
     */
    setConditionFlag(flag: number, value: boolean): void;

    /**
     * Gets the raw 32 bit patterns of the FPU (coprocessor 1) registers: element i is `$fi`, so
     * the array is always 32 long and in register order.
     *
     * The values are bit patterns, not numbers: read element i through `Float32Array`/`DataView`
     * for the single precision value. A double occupies an even/odd register pair, the low word
     * in the even register and the high word in the odd one that follows it, as MARS does: the
     * double held in `$f2` has element 2 as its low 32 bits and element 3 as its high 32 bits,
     * and an odd register alone holds no double.
     *
     * Each element is a signed 32 bit int, exactly like `getRegistersValues`: a value with the
     * top bit set reads back negative, so use `value >>> 0` for its unsigned form. The array
     * itself is an `Int32Array` at runtime, as `getRegistersValues` is, so `Array.isArray` is
     * false and `slice`/`map` return another `Int32Array` (whose `map` result is truncated back
     * to int32): copy it with `Array.from` when a real array is needed.
     */
    getCoprocessor1Values(): number[];

    /**
     * Sets one FPU register to a raw 32 bit pattern. Outside a Poke the write is direct: it records
     * no undo step, exactly like `setRegisterValue`. Inside a Poke it joins the open transaction.
     * @param index The register number, 0 to 31, `$f0` to `$f31`. It must be a whole number;
     * anything else, including a fractional index, throws.
     * @param value The 32 bit pattern to store.
     */
    setCoprocessor1Value(index: number, value: number): void;

    /**
     * Gets the values of the four implemented coprocessor 0 registers, in the fixed order
     * `$8 (vaddr)`, `$12 (status)`, `$13 (cause)`, `$14 (epc)` - the register numbers in
     * `MIPS_COPROCESSOR0_REGISTER_NUMBERS`. `status` reads 0x0000FF11 until an exception
     * changes it.
     *
     * Each element is a signed 32 bit int, exactly like `getRegistersValues`: a value with the
     * top bit set reads back negative, so use `value >>> 0` for its unsigned form. The array
     * itself is an `Int32Array` at runtime, as `getRegistersValues` is, so `Array.isArray` is
     * false and `slice`/`map` return another `Int32Array` (whose `map` result is truncated back
     * to int32): copy it with `Array.from` when a real array is needed.
     */
    getCoprocessor0Values(): number[];

    /**
     * Sets one coprocessor 0 register. Outside a Poke the write is direct: it records no undo step.
     * Inside a Poke it joins the open transaction.
     * @param number The register number, one of `MIPS_COPROCESSOR0_REGISTER_NUMBERS`
     * (8, 12, 13 or 14). Any other number throws. This is the register's MIPS number, not its
     * position in `getCoprocessor0Values()`.
     * @param value The 32 bit value to store.
     */
    setCoprocessor0Value(number: number, value: number): void;


    /**
     * Sets the maximum raw restore slots, before assembly. A Poke uses one slot; instructions
     * use one slot per restore. Oldest instructions are evicted whole. An instruction larger
     * than the capacity is discarded whole. Zero retains no history; negative sizes throw.
     * @param size
     */
    setUndoSize(size: number): void;

    /**
     * Undoes the newest entry of the history: the last instruction executed, or the last Poke made,
     * whichever is on top. Undoing a Poke restores every value it wrote and touches nothing else.
     */
    undo(): void;


    /**
     * Gets the statement at the given address.
     * @param address
     */
    getStatementAtAddress(address: number): JsProgramStatement;

    /** Gets every machine statement generated from an original source location. */
    getStatementsAtSourceLocation(sourcePath: string, sourceLine: number): JsProgramStatement[];


    getTokenizedLines(): MipsTokenizedLine[]
    /**
     * Checks if the simulation can be undone.
     * @returns True if the simulation can be undone, false otherwise.
     * */
    canUndo: boolean;



    /**
     * Gets the call stack.
     * @returns An array of memory addresses representing the call stack.
     */
    getCallStack(): JsMipsStackFrame[]



    /**
     * Gets the compiled statements.
     * @returns An array of `JsProgramStatement` objects representing the compiled program.
     */
    getCompiledStatements(): JsProgramStatement[]


    getParsedStatements(): JsProgramStatement[]


    getHi(): number;

    getLo(): number;


    /**
     * Gets the label at the given address.
     * @param address The memory address.
     * @returns The label at the given address, or null if no label is found.
     */
    getLabelAtAddress(address: number): string | null
    /** Address of a defined label/alias, local to the entry program or global, or -1 if absent. Requires successful assembly. */
    getAddressOfLabel(label: string): number

    /**
     * Where the program's heap, and so the first block sbrk (9) hands out, starts. MARS's heap base,
     * 0x10040000, unless the program is a `gnu-compiler-v1` Build whose static data (`.data`,
     * `.rodata`, `.bss`, common symbols) reaches past it: then the heap starts at the first 4 KiB page
     * after static data, where ld and a kernel put the break. A MARS-dialect program keeps the heap
     * base whatever its size, as MARS does. Requires successful assembly; `initialize` empties the
     * heap again.
     */
    getHeapStart(): number

    /**
     * Sets whether the undo feature is enabled.
     * @param enabled True to enable the undo feature, false to disable it.
     */
    setUndoEnabled(enabled: boolean): void;

    /**
     * Simulates until the program stops: an exit, running off the end, or a failure.
     * @returns A promise resolving to the reason the simulation stopped, rejecting with a
     * `RuntimeError` when the program fails.
     */
    simulate(): Promise<StopReason>;

    /**
     * Simulates the program for a limited number of instructions.
     * @param limit The maximum number of instructions to execute.
     * @returns A promise resolving to the reason the simulation stopped (`MAX_STEPS` when the
     * limit did), rejecting with a `RuntimeError` when the program fails.
     */
    simulateWithLimit(limit: number): Promise<StopReason>;

    /**
     * Simulates the program until a breakpoint is reached.
     * @param breakpoints An array of memory addresses where the simulation should pause.
     * @returns A promise resolving to the reason the simulation stopped, rejecting with a
     * `RuntimeError` when the program fails.
     */
    simulateWithBreakpoints(breakpoints: number[]): Promise<StopReason>;

    /**
     * Simulates the program with both breakpoints and a limit.
     * @param breakpoints An array of memory addresses where the simulation should pause.
     * @param limit The maximum number of instructions to execute.
     * @returns A promise resolving to the reason the simulation stopped, rejecting with a
     * `RuntimeError` when the program fails.
     */
    simulateWithBreakpointsAndLimit(breakpoints: number[], limit: number): Promise<StopReason>;

    /**
     * Gets the value of a register.
     * @param register The name of the register.
     * @returns The value of the register.
     */
    getRegisterValue(register: RegisterName): number;

    /**
     * Registers a handler function for a specific event or condition. Handlers are shared by every
     * `JsMips` instance. An optional handler (`randomSeed`) is removed by registering `undefined`.
     * @param name The name of the event or condition.
     * @param handler The handler function to be called when the event occurs. The function signature depends on the event name.
     */
    registerHandler<T extends HandlerName>(name: T, handler: HandlerFn<T> | (T extends OptionalHandlerName ? undefined : never)): void;

    /**
     * Gets the current value of the stack pointer.
     * @returns The value of the stack pointer.
     */
    stackPointer: number;

    /**
     * Gets the current value of the program counter.
     * @returns The value of the program counter.
     */
    programCounter: number;

    /**
     * Gets the values of all registers.
     * @returns An array containing the register values. The order of the values is implementation defined.
     */
    getRegistersValues(): number[];

    /**
     * Gets the undo stack, one element per back step, newest first. An instruction usually occupies
     * several of them - a `jal` restores both `$ra` and the program counter - while a Poke is
     * exactly one, the element with `isPoke` set, whatever it wrote. Use `getUndoGroups` to read
     * the history the way `undo()` pops it, one entry per instruction or Poke.
     * @returns An array of `JsBackStep` objects representing the history of the simulation.
     */
    getUndoStack(): JsBackStep[];

    /**
     * Gets the undo history grouped the way `undo()` pops it: one entry per executed instruction or
     * per Poke, newest first, each carrying the back steps it is made of. A Poke entry also carries
     * what it changed, with the old and the new value of each write.
     */
    getUndoGroups(): JsUndoGroup[];
    /**
     * The current dynamic instruction's serial, or null outside execution. Read it inside a host
     * handler to journal an effect under the same identity its eventual Undo group carries. It
     * remains stable while an async handler waits. Failures and exits have identities too.
     * Serials are allocated even with Undo disabled; such runs retain no groups. Treat the decimal
     * string as opaque (or compare with BigInt), never convert it to a JS number. Serials never
     * rewind or alias after Undo, initialize or reassembly; initialize clears retained history.
     */
    getCurrentInstructionSerial(): string | null;
    /**
     * The newest `max` entries of `getUndoGroups`, read from the top of the history without
     * grouping the rest of it: what a panel showing the latest steps of a large history wants.
     */
    getUndoGroupsUpTo(max: number): JsUndoGroup[];
    /** `max` entries of `getUndoGroups` after the newest `skip`, which are counted but never built. */
    getUndoGroupsRange(skip: number, max: number): JsUndoGroup[];
    /** How many entries `undo()` can still pop, counted the way `getUndoGroups` groups them. */
    getUndoDepth(): number;

    /**
     * Opens a Poke: a register or memory value changed by the host between two instructions,
     * recorded in this history as a step of its own.
     *
     * Until `endPoke` the setters - `setRegisterValue`, `setCoprocessor1Value`,
     * `setCoprocessor0Value`, `setConditionFlag` and `setMemoryBytes` - journal what they write
     * into the open transaction, however many of them are called, and `endPoke` records the lot as
     * one history entry that one `undo()` reverts and that takes one slot of the undo size, whether
     * it wrote one byte or a hundred. Outside a transaction the same setters stay direct and record
     * nothing, which is what presetting state needs.
     *
     * Throws if a Poke is already open, or if a `step`/`simulate*` call is still in flight.
     */
    beginPoke(): void;

    /**
     * Closes the open Poke.
     * @returns True if it recorded one history entry, false if nothing changed - or if undo is
     * disabled or its size is 0, in which case the writes stand but cannot be undone.
     * Throws if no Poke is open.
     */
    endPoke(): boolean;

    /** Whether a Poke is open, so that the setters journal rather than writing straight through. */
    pokeOpen(): boolean;

    /**
     * Reads a sequence of bytes from memory.
     *
     * Reading through this method notifies no memory observer: inspecting memory from the host is
     * not the program reading it, so a memory viewer never drives a memory-mapped register.
     * @param address The starting memory address.
     * @param length The number of bytes to read.
     * @returns An array of bytes read from memory.
     */
    readMemoryBytes(address: number, length: number): number[];

    /**
     * Writes a sequence of bytes to memory.
     *
     * Unlike `readMemoryBytes`, this writes the way the program does, so write observers are
     * notified and a memory mapped display repaints. It records no undo step of its own: a host
     * write is not an instruction, and recording it would make the next `undo()` revert it together
     * with the instruction that ran before it. Inside a Poke the same write joins the open
     * transaction instead, and a byte already holding the value written is skipped entirely.
     *
     * Use `setPeripheralWord` for a device keeping its own register up to date.
     * @param address The starting memory address.
     * @param bytes An array of bytes to write to memory.
     */
    setMemoryBytes(address: number, bytes: number[]): void;

    /**
     * Writes one word as a peripheral would: no observer is notified and no undo step is recorded,
     * because the write is not the program acting. This is how a device model refreshes a
     * memory-mapped register - a ready bit, a pending character - without feeding its own observer
     * or consuming undo history.
     * @param address The word address, which must be word-aligned. Either form of a high address
     * is accepted: `0xffff0000` and `0xffff0000 | 0` name the same word.
     * @param value The 32 bit value to store, raw, without byte-order adjustment.
     */
    setPeripheralWord(address: number, value: number): void;

    /**
     * Observes every write in an address range, the shape a framebuffer wants.
     *
     * Both addresses must be word-aligned, `endAddress` is inclusive and covers its whole word, and
     * the range may not cross 0x80000000 (split it in two registrations instead); a range that
     * breaks any of these throws. Either form of a high address is accepted: `0xffff0000` and
     * `0xffff0000 | 0` name the same word. The handler runs synchronously inside the storing instruction, so
     * it must be cheap and must not write back into its own range; a returned promise is ignored.
     *
     * Observers live on the simulator's memory, which assembling and initializing only clear the
     * contents of, so a registration survives `assemble()` and `initialize()`. For the same reason
     * it is shared by every `JsMips` instance: register once per page, or remove the previous
     * registration before registering again for a newly built program.
     *
     * Notifications only start once a program has been assembled, and undo notifies too: restoring
     * memory during `undo()` goes through the same stores, so an observed range reports the
     * restored values as ordinary writes.
     * @returns A handle for `removeMemoryObserver`.
     */
    addMemoryWriteObserver(startAddress: number, endAddress: number, handler: MemoryWriteObserver): MemoryObserverHandle;

    /**
     * Observes reads and writes of a single word, the shape a memory-mapped register wants. The
     * address must be word-aligned. Pass `null` for a direction you do not care about. The same
     * lifetime and synchronous-handler rules as `addMemoryWriteObserver` apply.
     * @returns A handle for `removeMemoryObserver`.
     */
    addMemoryAccessObserver(address: number, onRead: MemoryAccessObserver | null, onWrite: MemoryAccessObserver | null): MemoryObserverHandle;

    /**
     * Removes one registration. An unknown handle is ignored.
     */
    removeMemoryObserver(handle: MemoryObserverHandle): void;

    /**
     * Removes every registration.
     */
    removeMemoryObservers(): void;

    /**
     * The number of live registrations, across every `JsMips` instance.
     */
    countMemoryObservers(): number;

    /**
     * Gets the next statement to be executed.
     * @returns The next `JsProgramStatement`, or null once the program has ended (`terminated`):
     * after an exit the statement that follows the syscall is not one the program will run.
     */
    getNextStatement(): JsProgramStatement | null;

    /**
     * Sets the value of a register. Outside a Poke the write is direct: it records no undo step.
     * Inside a Poke it joins the open transaction, except for `$zero`, which holds no value and so
     * is left alone.
     * @param register The name of the register.
     * @param value The value to set the register to.
     */
    setRegisterValue(register: RegisterName, value: number): void;

    /**
     * Whether the program has ended, read from its state rather than from the last run call, so
     * that it is right after `undo()` too: an exit service has run, or there is no statement at
     * the program counter because execution ran off the end. It is true as soon as the last
     * instruction has run. A runtime failure does not set it: the run call's rejection reports it.
     */
    readonly terminated: boolean;
}



/**
 * Creates a MIPS simulator from a virtual source tree and its entry file.
 *
 * Source paths are canonical, root-relative, case-sensitive POSIX paths. The source set is
 * snapshotted by this call; only the entry file and files reached through `.include` are assembled.
 * @param files Source text keyed by canonical source path.
 * @param entryFile Canonical path of the file from which include expansion starts.
 * @param options The assembler profile, the entry symbol and the libraries to link; see `AssemblyOptions`.
 * @returns A new `JsMips` object.
 */
export function makeMipsFromFiles(files: MIPSSourceSet, entryFile: string, options?: AssemblyOptions): JsMips {
    if (options !== undefined && (options === null || typeof options !== 'object' || Array.isArray(options))) {
        throw new TypeError('Assembly options must be an object')
    }
    const profile = options && Object.hasOwn(options, 'assemblerProfile') ? options.assemblerProfile : 'mars'
    if (profile !== 'mars' && profile !== 'gnu-compiler-v1') {
        throw new TypeError(`Unsupported assembler profile: ${String(profile)}`)
    }
    const entrySymbol = options && Object.hasOwn(options, 'entrySymbol') ? options.entrySymbol : ''
    if (typeof entrySymbol !== 'string' || (Object.hasOwn(options ?? {}, 'entrySymbol') && !/^[.$A-Za-z_][.$A-Za-z_0-9]*$/.test(entrySymbol))) {
        throw new TypeError(`Invalid entry symbol: ${String(entrySymbol)}`)
    }
    const memberPaths: string[] = [], memberSources: string[] = [], indexSymbols: string[] = [], indexMembers: string[] = [], resolveWeak: string[] = []
    const libraries = options && Object.hasOwn(options, 'libraries') ? options.libraries : []
    if (!Array.isArray(libraries)) throw new TypeError('Libraries must be an array')
    for (const library of libraries) {
        if (library === null || typeof library !== 'object' || library.members === null || typeof library.members !== 'object' ||
            library.index === null || typeof library.index !== 'object') {
            throw new TypeError('A library must have members and an index')
        }
        for (const [path, source] of Object.entries(library.members)) {
            if (typeof source !== 'string') throw new TypeError(`Library member source must be a string: ${path}`)
            if (memberPaths.includes(path)) throw new TypeError(`Duplicate library member: ${path}`)
            memberPaths.push(path)
            memberSources.push(source)
        }
        for (const [symbol, member] of Object.entries(library.index)) {
            if (typeof member !== 'string' || !Object.hasOwn(library.members, member)) {
                throw new TypeError(`Library index names a missing member: ${String(member)}`)
            }
            indexSymbols.push(symbol)
            indexMembers.push(member)
        }
        const weak = library.resolveWeak ?? []
        if (!Array.isArray(weak)) throw new TypeError('resolveWeak must list symbol names')
        for (const name of weak) {
            if (typeof name !== 'string') throw new TypeError('resolveWeak must list symbol names')
            resolveWeak.push(name)
        }
    }
    if (files === null || typeof files !== 'object' || Array.isArray(files)) {
        throw new TypeError('Source set must be an object')
    }
    if (typeof entryFile !== 'string') {
        throw new TypeError('Entry file must be a string')
    }
    const entries = Object.entries(files)
    for (const [sourcePath, source] of entries) {
        if (typeof source !== 'string') {
            throw new TypeError(`Source content must be a string: ${sourcePath}`)
        }
    }
    initializeMIPS()
    return _makeMipsFromFilesWithOptions(
        entries.map(([sourcePath]) => sourcePath),
        entries.map(([, source]) => source),
        entryFile,
        profile,
        entrySymbol,
        memberPaths,
        memberSources,
        indexSymbols,
        indexMembers,
        resolveWeak,
    ) as JsMips
}

/**
 * Initializes the MIPS simulator.
 */
function initializeMIPS(): void {
    _initializeMIPS()
}
